name: Luacheck

on:
    workflow_dispatch:
    pull_request:
        branches:
            - develop
            - main
        paths:
            - '**'

jobs:
    luacheck:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Luacheck linter
                uses: lunarmodules/luacheck@v1