name: 'Tests'

on:
    workflow_dispatch:
    pull_request:

permissions:
    contents: read
    packages: read

jobs:
    lua-tests:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        container:
            image: ghcr.io/blockydevs/arns-marketplace-process-tests
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Run UCM tests
                run: |
                    cd tests
                    lua ucm_tests.lua

            -   name: Run Dutch auction tests
                run: |
                    cd tests
                    lua dutch_tests.lua

            -   name: Run general tests
                run: |
                    cd tests
                    lua tests.lua

    node-tests:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: '18'

            -   name: Install Node.js dependencies
                run: |
                    cd tests/node
                    npm install

            -   name: Run Node.js tests
                run: |
                    cd tests/node
                    npm test