name: 'Tests'

on:
    workflow_dispatch:
    pull_request:

permissions:
    contents: read
    packages: read

jobs:
    unit:
        runs-on: ubuntu-24.04
        timeout-minutes: 10
        steps:
            -   name: Check out repository code
                uses: actions/checkout@v4

            -   name: Setup Lua
                uses: leafo/gh-actions-lua@v10
                with:
                    luaVersion: '5.3'

            -   name: Setup LuaRocks
                uses: leafo/gh-actions-luarocks@v4.3.0

            -   name: Install Lua dependencies
                run: |
                    luarocks make --only-deps arns-marketplace-process-0.1.0-1.rockspec

            -   name: Run UCM tests
                if: ${{ always() }}
                run: |
                    cd tests
                    lua ucm_tests.lua

            -   name: Run Dutch auction tests
                if: ${{ always() }}
                run: |
                    cd tests
                    lua dutch_tests.lua

            -   name: Run general tests
                if: ${{ always() }}
                run: |
                    cd tests
                    lua tests.lua

            -   name: Run activity tests
                if: ${{ always() }}
                run: |
                    cd tests
                    lua activity_tests.lua

            -   name: Run english tests
                if: ${{ always() }}
                run: |
                    cd tests
                    lua english_tests.lua